### ISSUE TITLE
Interest in contribution

### ISSUE THREAD

**Issue by pelord** [pelord/sorry#1]
Hi Andrea.
@ahocevar
Sorry to bother you.  If you do not reply to me, I will understand.

I using each day Openlayers at my job, by developping a web app name IGO2 (https://github.com/infra-geo-ouverte/igo2  and a demo https://infra-geo-ouverte.github.io/igo2/ )

I sometime find some bug/issues in openlayers and I feel ready to contribute to Openlayers. I would like to know if you have some "how to start developping into openlayers" documentation.

Thanks for your extraordinary job done for openlayers! It is much appreciated.

**Comment by pelord** [comment]
I think it is quite simple...

npm install 
+ 
npm run build-package
+
npm start 
+ debug the examples?

**Comment by ahocevar** [comment]
Actually it's only `npm install` and `npm start`. Then you can debug the examples in your browser (http://localhost:8080).
